### ISSUE TITLE
arm64 binary missing?

### ISSUE THREAD

**Issue by AeliusSaionji** [hazae41/sweet-ipfs#13]
There appears to be no binary for armd64. I just get "file not found" when I try to start the daemon.

**Comment by lordcirth** [comment]
Do you mean arm64? I get this too.

**Comment by AeliusSaionji** [comment]
Yes, sorry.

**Comment by AeliusSaionji** [comment]
Would love to use this app! Should be a simple fix to package the binary and push a release, no?

**Comment by wschenk** [comment]
I"m trying to install on a pixelbook and I think I'm running into the same issue.  Anyone have a work around?

**Comment by realkarmakun** [comment]
I met same issue. It's not fixed since January?

**Comment by kristianlm** [comment]
I am getting an issue that must be the s'me one:

![Screenshot_20190423-154302](https://user-images.githubusercontent.com/259445/56585705-a6f91e80-65de-11e9-979b-f70b3715c545.png)_

**Comment by rafaelekol** [comment]
Binary files are downloaded at app compile time from this url https://dist.ipfs.io/go-ipfs/. You can see this code in gradle file. Also you can check project directory where these binaries stored `app/assets/` 
I goes something goes wrong in your case.

**Comment by kristianlm** [comment]
I'm talking about if the current [official F-Droid one](https://f-droid.org/en/packages/fr.rhaz.ipfs.sweet/), not my own.

I've looked inside the apk-file to try and find some binaries without any luck (but maybe they're hidden inside `resources.arsc` or something). I'm not really sure how to verify this.

**Comment by rafaelekol** [comment]
When I install this app from PlayStore, it weights almost 50 mb. When I was unpacking apk, built  from this source, I could see binary files inside assets directory.

**Comment by AeliusSaionji** [comment]
Confirmed: the play store version works.

**Comment by ZerataX** [comment]
why is this closed? the fdroid build is still broken?
