### ISSUE TITLE
"arm" & "x86" libraries 

### ISSUE THREAD

**Issue by IordacheClaudiu** [hazae41/sweet-ipfs#18]
Hi,

I made a fork from your repo months ago and I was wondering how the `arm` and `x86` libraries were generated?

Best regards.

**Comment by hazae41** [comment]
https://github.com/hazae41/sweet-ipfs/blob/dev/app/binaries.gradle

They are generated here

**Comment by IordacheClaudiu** [comment]
Thanks 😃
